name: 🕹️ Suggest a New Game
description: Propose a new game for odyc.dev
title: "[New Game] "
labels: ["new game"]
body:
  - type: input
    id: url
    attributes:
      label: Game URL
      placeholder: https://...
    validations:
      required: true
